version: '3.3'
services:
  app:
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    volumes:
      - node_modules:/app/node_modules
      - ./cache:/app/cache
      - ./input:/app/input
      - ./output:/app/output
      - ./app:/app/
    tty: true
volumes:
  node_modules:
