import type { Metadata } from "next";
import Provider from "@/app/Provider";
import { ReactNode } from "react";
import "leaflet/dist/leaflet.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
